# render.yaml

services:
  # 1. Redis broker (used by Celery)
  - type: redis
    name: redis-broker
    plan: free
    ipAllowList: []

  # 2. Django Backend API Service
  - type: web
    name: backend-api
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        value: SECRET_KEY
      - key: DATABASE_URL
        value: DATABASE_URL
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-broker
          property: connectionString
      - key: OPENAI_API_KEY
        value: OPENAI_API_KEY
      - key: GMAIL_APP_PASSWORD
        value: GMAIL_APP_PASSWORD
      - key: GOOGLE_API_KEY
        value: GOOGLE_API_KEY
      - key: CLOUDINARY_CLOUD_NAME
        value: CLOUDINARY_CLOUD_NAME
      - key: CLOUDINARY_API_KEY
        value: CLOUDINARY_API_KEY
      - key: CLOUDINARY_API_SECRET
        value: CLOUDINARY_API_SECRET
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: yourdomain.com

  # 3. Celery Worker Service
  - type: worker
    name: celery-worker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A backend.celery worker -l info"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        value: SECRET_KEY
      - key: DATABASE_URL
        value: DATABASE_URL
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-broker
          property: connectionString
      - key: OPENAI_API_KEY
        value: OPENAI_API_KEY
      - key: GMAIL_APP_PASSWORD
        value: GMAIL_APP_PASSWORD
      - key: GOOGLE_API_KEY
        value: GOOGLE_API_KEY
      - key: CLOUDINARY_CLOUD_NAME
        value: CLOUDINARY_CLOUD_NAME
      - key: CLOUDINARY_API_KEY
        value: CLOUDINARY_API_KEY
      - key: CLOUDINARY_API_SECRET
        value: CLOUDINARY_API_SECRET
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: yourdomain.com
