services:
  - type: redis
    name: redis-broker
    plan: free
    ipAllowList: []

  - type: web
    name: backend-api
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: ENVIRONMENT
        value: production
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: DATABASE_URL
        value: postgres://user:pass@host:5432/dbname
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: yourdomain.com
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-broker
          property: connectionString

  - type: worker
    name: celery-worker
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery -A backend.celery worker -l info"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: ENVIRONMENT
        value: production
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        value: your-secret-key-here
      - key: DATABASE_URL
        value: postgres://user:pass@host:5432/dbname
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: yourdomain.com
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-broker
          property: connectionString
