# Generated by Django 5.1.7 on 2025-06-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_register', '0003_remove_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='district',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
