# Generated by Django 5.1.7 on 2025-06-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_and_register', '0004_vendor_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='district',
        ),
        migrations.AddField(
            model_name='customuser',
            name='district',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
