# Generated by Django 5.1.7 on 2025-07-02 16:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminCorrectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(blank=True, choices=[('cpu', 'CPU'), ('gpu', 'GPU'), ('disk', 'Disk')], help_text='The type of component being corrected (CPU, GPU, Disk).', max_length=10, null=True)),
                ('original_text', models.CharField(blank=True, help_text='The text the AI tried to match.', max_length=255, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('intensity_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('source', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationExtractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_ai_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationSystemRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('minimum', 'Minimum'), ('recommended', 'Recommended')], max_length=20)),
                ('cpu', models.CharField(max_length=255)),
                ('gpu', models.CharField(max_length=255)),
                ('cpu_score', models.IntegerField(blank=True, null=True)),
                ('gpu_score', models.IntegerField(blank=True, null=True)),
                ('ram', models.IntegerField(help_text='RAM in GB')),
                ('storage_size', models.IntegerField(help_text='Storage in GB')),
                ('storage_type', models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD'), ('Any', 'Any')], default='Any', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CPUBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(help_text='The full, original name from the benchmark source.', max_length=255, unique=True)),
                ('model_name', models.CharField(db_index=True, help_text="The clean model name, e.g., 'Intel Core i9-9960X'", max_length=200)),
                ('clock_speed_ghz', models.DecimalField(blank=True, decimal_places=2, help_text='The clock speed in GHz, if available.', max_digits=4, null=True)),
                ('score', models.IntegerField()),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('value_score', models.FloatField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('embedding', models.TextField(blank=True, help_text='JSON-serialized 768-dim vector embedding.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiskBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_name', models.CharField(max_length=255, unique=True)),
                ('size_tb', models.FloatField(blank=True, null=True)),
                ('score', models.IntegerField()),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('value_score', models.FloatField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPUBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu', models.CharField(help_text="The full, original name from the benchmark source, e.g., 'NVIDIA GeForce RTX 4090'", max_length=255, unique=True)),
                ('model_name', models.CharField(db_index=True, help_text="The clean model name, e.g., 'GeForce RTX 4090'", max_length=200)),
                ('score', models.IntegerField()),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('value_score', models.FloatField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('embedding', models.TextField(blank=True, help_text='JSON-serialized 768-dim vector embedding.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('recommended', 'Recommended'), ('minimum', 'Minimum')], default='recommended', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_cpu_name', models.CharField(blank=True, max_length=255, null=True)),
                ('recommended_gpu_name', models.CharField(blank=True, max_length=255, null=True)),
                ('recommended_cpu_score', models.IntegerField(blank=True, null=True)),
                ('recommended_gpu_score', models.IntegerField(blank=True, null=True)),
                ('recommended_ram', models.IntegerField(blank=True, null=True)),
                ('recommended_storage_size', models.IntegerField(blank=True, null=True)),
                ('recommended_storage_type', models.CharField(default='Any', max_length=10)),
                ('min_cpu_name', models.CharField(blank=True, max_length=255, null=True)),
                ('min_gpu_name', models.CharField(blank=True, max_length=255, null=True)),
                ('min_cpu_score', models.IntegerField(blank=True, null=True)),
                ('min_gpu_score', models.IntegerField(blank=True, null=True)),
                ('min_ram', models.IntegerField(blank=True, null=True)),
                ('min_storage_size', models.IntegerField(blank=True, null=True)),
                ('min_storage_type', models.CharField(default='Any', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities_json', models.JSONField(help_text='Snapshot of activity names')),
                ('applications_json', models.JSONField(help_text='Snapshot of application data that was considered')),
                ('admin_rating', models.IntegerField(blank=True, choices=[(3, 'Excellent'), (2, 'Good'), (1, 'Poor'), (0, 'Incorrect')], db_index=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text="Why this rating was given, e.g., 'Recommended a Pentium 4, which is too old.'")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementExtractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_cpu', models.CharField(blank=True, max_length=255, null=True)),
                ('extracted_gpu', models.CharField(blank=True, max_length=255, null=True)),
                ('extracted_ram', models.IntegerField(blank=True, null=True)),
                ('extracted_storage', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True, help_text='The raw text that was processed to extract these requirements.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_confidence', models.FloatField(default=0.0)),
                ('gpu_confidence', models.FloatField(default=0.0)),
                ('match_method', models.CharField(default='exact', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('app_count', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemRequirementExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField()),
                ('raw_text', models.TextField()),
                ('extracted_cpu', models.CharField(blank=True, max_length=255)),
                ('extracted_gpu', models.CharField(blank=True, max_length=255)),
                ('extracted_ram', models.IntegerField(blank=True, null=True)),
                ('extracted_storage', models.IntegerField(blank=True, null=True)),
                ('extraction_method', models.CharField(default='rule-based', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
