# Generated by Django 5.1.7 on 2025-07-02 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpubenchmark',
            old_name='name',
            new_name='cpu',
        ),
        migrations.RenameField(
            model_name='gpubenchmark',
            old_name='name',
            new_name='gpu',
        ),
    ]
