# Generated by Django 5.1.7 on 2025-06-11 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommender', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationExtractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('extracted_apps', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('reviewed', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_recommender.activity')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementExtractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField()),
                ('extracted_json', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(default='regex', max_length=50)),
                ('confidence', models.FloatField(null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_recommender.application')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_confidence', models.FloatField(default=0.0)),
                ('gpu_confidence', models.FloatField(default=0.0)),
                ('match_method', models.CharField(default='exact', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('matched_cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_recommender.cpubenchmark')),
                ('matched_gpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_recommender.gpubenchmark')),
            ],
        ),
        migrations.CreateModel(
            name='AdminCorrectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('corrected_cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_cpu', to='ai_recommender.cpubenchmark')),
                ('corrected_gpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrected_gpu', to='ai_recommender.gpubenchmark')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_recommender.requirementmatch')),
            ],
        ),
        migrations.CreateModel(
            name='ScrapingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('app_count', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_recommender.activity')),
            ],
        ),
        migrations.CreateModel(
            name='SystemRequirementExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField()),
                ('raw_text', models.TextField()),
                ('extracted_cpu', models.CharField(blank=True, max_length=255)),
                ('extracted_gpu', models.CharField(blank=True, max_length=255)),
                ('extracted_ram', models.IntegerField(blank=True, null=True)),
                ('extracted_storage', models.IntegerField(blank=True, null=True)),
                ('extraction_method', models.CharField(default='rule-based', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_recommender.application')),
            ],
        ),
        migrations.AddField(
            model_name='requirementmatch',
            name='extraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_recommender.systemrequirementextraction'),
        ),
    ]
