# Generated by Django 5.1.7 on 2025-07-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommender', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='considerations',
            field=models.TextField(blank=True, help_text="User's other preferences, e.g., 'lightweight', 'budget around $1000'."),
        ),
    ]
