# Generated by Django 5.1.7 on 2025-07-02 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommender', '0002_rename_name_cpubenchmark_cpu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpubenchmark',
            name='embedding',
            field=models.TextField(blank=True, help_text='JSON-serialized 768-dim vector embedding.', null=True),
        ),
        migrations.AddField(
            model_name='gpubenchmark',
            name='embedding',
            field=models.TextField(blank=True, help_text='JSON-serialized 768-dim vector embedding.', null=True),
        ),
        migrations.CreateModel(
            name='ActivitySimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jaccard_similarity', models.FloatField(help_text='Similarity based on common applications (0 to 1)')),
                ('requirement_similarity', models.FloatField(help_text='Similarity based on system requirement scores (0 to 1)')),
                ('combined_score', models.FloatField(db_index=True, help_text='Weighted average of both similarities')),
                ('source_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_sources', to='ai_recommender.activity')),
                ('target_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_targets', to='ai_recommender.activity')),
            ],
            options={
                'ordering': ['-combined_score'],
                'unique_together': {('source_activity', 'target_activity')},
            },
        ),
    ]
