# Generated by Django 5.1.7 on 2025-07-02 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommender', '0003_cpubenchmark_embedding_gpubenchmark_embedding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities_json', models.JSONField(help_text='Snapshot of activity names')),
                ('applications_json', models.JSONField(help_text='Snapshot of application data that was considered')),
                ('admin_rating', models.IntegerField(blank=True, choices=[(3, 'Excellent'), (2, 'Good'), (1, 'Poor'), (0, 'Incorrect')], db_index=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text="Why this rating was given, e.g., 'Recommended a Pentium 4, which is too old.'")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('final_recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ai_recommender.recommendationspecification')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_preference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_recommender.userpreference')),
            ],
        ),
    ]
