# Generated by Django 5.1.7 on 2025-07-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommender', '0003_userpreference_considerations'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationspecification',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='A human-friendly summary of the recommendation, generated by the AI.', null=True),
        ),
        migrations.AddField(
            model_name='recommendationspecification',
            name='ai_title',
            field=models.CharField(blank=True, help_text='A human-friendly title generated by the AI.', max_length=255, null=True),
        ),
    ]
