# Generated by Django 5.1.7 on 2025-06-20 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommender', '0003_applicationextractionlog_requirementextractionlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='preference',
        ),
        migrations.RenameField(
            model_name='gpubenchmark',
            old_name='cpu',
            new_name='gpu',
        ),
        migrations.RenameField(
            model_name='gpubenchmark',
            old_name='cpu_mark',
            new_name='gpu_mark',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='custom_applications',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='profession',
        ),
        migrations.AddField(
            model_name='recommendationspecification',
            name='recommended_cpu_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationspecification',
            name='recommended_gpu_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationspecification',
            name='recommended_ram',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationspecification',
            name='recommended_storage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationspecification',
            name='source_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_recommender.userpreference'),
        ),
        migrations.AddField(
            model_name='recommendationspecification',
            name='type',
            field=models.CharField(choices=[('recommended', 'Recommended'), ('minimum', 'Minimum')], default='recommended', max_length=20),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='applications',
            field=models.ManyToManyField(blank=True, to='ai_recommender.application'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
