# Generated by Django 5.1.7 on 2025-06-23 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommender', '0004_remove_useranswer_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpubenchmark',
            name='cpu_mark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cpubenchmark',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
        ),
        migrations.AlterField(
            model_name='gpubenchmark',
            name='gpu_mark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gpubenchmark',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=65, null=True),
        ),
    ]
