# Generated by Django 5.1.7 on 2025-06-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommender', '0004_remove_useranswer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationspecification',
            name='min_cpu_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recommendationspecification',
            name='min_gpu_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recommendationspecification',
            name='recommended_cpu_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recommendationspecification',
            name='recommended_gpu_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
