# Generated by Django 5.1.7 on 2025-06-26 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommender', '0005_alter_cpubenchmark_cpu_mark_alter_cpubenchmark_price_and_more'),
        ('ai_recommender', '0005_recommendationspecification_min_cpu_name_and_more'),
    ]

    operations = [
    ]
