# Generated by Django 5.1.7 on 2025-06-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommender', '0006_merge_20250626_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_name', models.CharField(max_length=255, unique=True)),
                ('size_tb', models.FloatField(blank=True, null=True)),
                ('score', models.IntegerField()),
                ('value_score', models.FloatField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='applicationsystemrequirement',
            old_name='storage',
            new_name='storage_size',
        ),
        migrations.RenameField(
            model_name='recommendationspecification',
            old_name='recommended_storage',
            new_name='min_storage_size',
        ),
        migrations.RemoveField(
            model_name='cpubenchmark',
            name='cpu_mark',
        ),
        migrations.RemoveField(
            model_name='gpubenchmark',
            name='gpu_mark',
        ),
        migrations.RemoveField(
            model_name='recommendationspecification',
            name='min_storage',
        ),
        migrations.AddField(
            model_name='applicationsystemrequirement',
            name='storage_score',
            field=models.IntegerField(blank=True, help_text='Target score from DiskBenchmark', null=True),
        ),
        migrations.AddField(
            model_name='applicationsystemrequirement',
            name='storage_type',
            field=models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD'), ('Any', 'Any')], default='Any', max_length=10),
        ),
        migrations.AddField(
            model_name='cpubenchmark',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpubenchmark',
            name='value_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpubenchmark',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpubenchmark',
            name='value_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationspecification',
            name='min_storage_type',
            field=models.CharField(default='Any', max_length=10),
        ),
        migrations.AddField(
            model_name='recommendationspecification',
            name='recommended_storage_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendationspecification',
            name='recommended_storage_type',
            field=models.CharField(default='Any', max_length=10),
        ),
        migrations.AlterField(
            model_name='cpubenchmark',
            name='cpu',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='cpubenchmark',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gpubenchmark',
            name='gpu',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='gpubenchmark',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='recommendationspecification',
            name='min_cpu_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendationspecification',
            name='min_gpu_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendationspecification',
            name='min_ram',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendationspecification',
            name='recommended_cpu_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendationspecification',
            name='recommended_gpu_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
