# Generated by Django 5.1.7 on 2025-06-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommender', '0007_diskbenchmark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diskbenchmark',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
