# Generated by Django 5.1.7 on 2025-06-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_recommender', '0008_diskbenchmark_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationsystemrequirement',
            name='storage_score',
        ),
        migrations.AlterField(
            model_name='applicationsystemrequirement',
            name='cpu_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationsystemrequirement',
            name='gpu_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
